# -----------------------------------------
# ServiceAccount untuk Prometheus & Grafana
# -----------------------------------------
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: kautsarhaqi-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: kautsarhaqi-dev

# -----------------------------------------
# Role & RoleBinding (namespace-scope)
# -----------------------------------------
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-rolebinding
  namespace: kautsarhaqi-dev
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: kautsarhaqi-dev
roleRef:
  kind: Role
  name: prometheus-role
  apiGroup: rbac.authorization.k8s.io

# -----------------------------------------
# ConfigMap untuk Prometheus Config
# -----------------------------------------

# -----------------------------------------
# Deployment Prometheus
# -----------------------------------------
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: kautsarhaqi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: kautsarhaqi-dev
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090

# -----------------------------------------
# Deployment Grafana
# -----------------------------------------
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: kautsarhaqi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      serviceAccountName: grafana
      containers:
        - name: grafana
          image: grafana/grafana
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: kautsarhaqi-dev
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
